var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(pages)/verify/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__aeaf2d28._.js")
R.c("server/chunks/ssr/node_modules_8c3db903._.js")
R.c("server/chunks/ssr/node_modules_next_dist_7da8c22c._.js")
R.c("server/chunks/ssr/app_0ef037c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e5e82eab._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__ebf15b87._.js")
R.c("server/chunks/ssr/_993f36f0._.js")
R.c("server/chunks/ssr/_f1279803._.js")
R.m(43761)
R.m(73864)
module.exports=R.m(73864).exports
