export enum PropertyTypeEnum {
  STUDIO = 'STUDIO',
  HOUSE = 'HOUSE',
  VILLA = 'VILLA',
  APARTMENT = 'APARTMENT',
  DUPLEX = 'DUPLEX',
}

export enum StatusEnum {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING = 'PENDING',
  DRAFT = 'DRAFT',
}

export enum EnergyRatingEnum {
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
  E = 'E',
  F = 'F',
  G = 'G',
}

export enum OrientationEnum {
  N = 'N',
  NE = 'NE',
  E = 'E',
  SE = 'SE',
  S = 'S',
  SW = 'SW',
  W = 'W',
  NW = 'NW',
}

export enum ParkingEnum {
  NONE = 'NONE',
  GARAGE = 'GARAGE',
  DRIVEWAY = 'DRIVEWAY',
  STREET_PARKING = 'STREET_PARKING',
}

export enum BalconyTypeEnum {
  NONE = 'NONE',
  BALCONY = 'BALCONY',
  TERRACE = 'TERRACE',
  BOTH = 'BOTH',
}

export enum HeatingSystemEnum {
  CENTRAL = 'CENTRAL',
  UNDERFLOOR = 'UNDERFLOOR',
  GAS = 'GAS',
  ELECTRIC = 'ELECTRIC',
}

export enum CoolingSystemEnum {
  AC = 'AC',
  VENTILATION = 'VENTILATION',
}

export enum KitchenEnum {
  FURNISHED = 'FURNISHED',
  APPLIENCES = 'APPLIENCES',
}

export enum SecurityEnum {
  ALARM_SYSTEM = 'ALARM_SYSTEM',
  CAMERAS = 'CAMERAS',
  GATED_ACCESS = 'GATED_ACCESS',
}

export enum UtilityEnum {
  FIBER = 'FIBER',
  CABLE = 'CABLE',
  WATER = 'WATER',
  GAS = 'GAS',
  ELECTRICITY = 'ELECTRICITY',
}

export enum SmartHomeFeatureEnum {
  THERMOSTAT = 'THERMOSTAT',
  LIGHTING = 'LIGHTING',
  LOCKS = 'LOCKS',
}

export enum OtherFeatureEnum {
  SWIMMING_POOL = 'SWIMMING_POOL',
  SAUNA = 'SAUNA',
  JACUZZI = 'JACUZZI',
  FIREPLACE = 'FIREPLACE',
  BBQ_AREA = 'BBQ_AREA',
  OUTDOOR_KITCHEN = 'OUTDOOR_KITCHEN',
}

export enum InvestmentGoalTagEnum {
  HIGH_ROI = 'HIGH_ROI',
  CASH_FLOW_POSITIVE = 'CASH_FLOW_POSITIVE',
  SHORT_TERM_RENTAL_READY = 'SHORT_TERM_RENTAL_READY',
  LONG_TERM_RENTAL_STABLE = 'LONG_TERM_RENTAL_STABLE',
  FIX_AND_FLIP = 'FIX_AND_FLIP',
  NEW_DEVELOPMENT = 'NEW_DEVELOPMENT',
  BELOW_MARKET_VALUE = 'BELOW_MARKET_VALUE',
  TURNKEY_INVESTMENT = 'TURNKEY_INVESTMENT',
  MULTI_UNIT = 'MULTI_UNIT',
  STUDENT_HOUSING = 'STUDENT_HOUSING',
  RETIREMENT_INCOME = 'RETIREMENT_INCOME',
  VACATION_HOME_INCOME = 'VACATION_HOME_INCOME',
  COMMERCIAL_CONVERSION = 'COMMERCIAL_CONVERSION',
}

export enum LocationBenefitTagEnum {
  TAX_FREE_ZONE = 'TAX_FREE_ZONE',
  LOW_PROPERTY_TAX = 'LOW_PROPERTY_TAX',
  URBAN_GROWTH_ZONE = 'URBAN_GROWTH_ZONE',
  TOURIST_HOTSPOT = 'TOURIST_HOTSPOT',
  NEAR_INFRASTUCTURE_PROJECT = 'NEAR_INFRASTUCTURE_PROJECT',
  ECONOMIC_HUB = 'ECONOMIC_HUB',
  EXPAT_FRIENDLY = 'EXPAT_FRIENDLY',
  GREEN_ZONE = 'GREEN_ZONE',
  HERITAGE_ZONE = 'HERITAGE_ZONE',
  SAFE_NEIGHBORHOOD = 'SAFE_NEIGHBORHOOD',
  SCHOOL_DISTRICT = 'SCHOOL_DISTRICT',
  COASTAL_ACCESS = 'COASTAL_ACCESS',
  MOUNTAIN_VIEW = 'MOUNTAIN_VIEW',
  EU_RESIDENCY_ELIGIBLE = 'EU_RESIDENCY_ELIGIBLE',
  GOLDEN_VISA = 'GOLDEN_VISA',
}