// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/(pages)/(home)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(pages)/(home)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/agency/changePassword/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/changePassword">> = Specific
  const handler = {} as typeof import("../../app/(pages)/agency/changePassword/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/agency/logOut/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agency/logOut">> = Specific
  const handler = {} as typeof import("../../app/(pages)/agency/logOut/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/agencyDashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agencyDashboard">> = Specific
  const handler = {} as typeof import("../../app/(pages)/agencyDashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/createProperty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/createProperty">> = Specific
  const handler = {} as typeof import("../../app/(pages)/createProperty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/details">> = Specific
  const handler = {} as typeof import("../../app/(pages)/details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/investorsDashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investorsDashboard">> = Specific
  const handler = {} as typeof import("../../app/(pages)/investorsDashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/(pages)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/propertiesDashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/propertiesDashboard">> = Specific
  const handler = {} as typeof import("../../app/(pages)/propertiesDashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/(pages)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/user/changePassword/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/changePassword">> = Specific
  const handler = {} as typeof import("../../app/(pages)/user/changePassword/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/user/logOut/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user/logOut">> = Specific
  const handler = {} as typeof import("../../app/(pages)/user/logOut/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/user/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/user">> = Specific
  const handler = {} as typeof import("../../app/(pages)/user/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(pages)/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify">> = Specific
  const handler = {} as typeof import("../../app/(pages)/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
